spring:
  application:
    name: eureka-server
  profiles:
    active: local
  config:
    import: optional:file:.env[.properties]
  cloud:
    config:
      enabled: false

server:
  port: ${SERVER_PORT}

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:${SERVER_PORT}/eureka/